from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, TextSubstitution, PathJoinSubstitution, PythonExpression
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node
from moveit_configs_utils import MoveItConfigsBuilder
import os
from ament_index_python.packages import get_package_share_directory

# For customizing features of this Launchfile, refer to the official MoveIt2 launches [https://moveit.picknik.ai/main/api/html/launches_8py_source.html]
# OBS: standard MoveIt2 launches expects all files to be in the same package in specific paths and under specific names, as generated by the moveit_setup_assistant, 
# our files are divided across all packages from utbots_manipulation with different names (such as theseus_controllers). 

def generate_launch_description():
    is_sim_arg = DeclareLaunchArgument(
        "is_sim",
        default_value="False"
    )

    is_sim = LaunchConfiguration("is_sim")

    model_arg = DeclareLaunchArgument(
        name="model", 
        default_value=os.path.join(get_package_share_directory("theseus_description"), "urdf", "theseus.urdf.xacro"),
        description="Absolute path to the robot URDF file"
    )

    # Build the robot_description using xacro
    # xacro_filename = os.path.join(get_package_share_directory("theseus_description"), "urdf",  PythonExpression(["'", LaunchConfiguration("model"), "'"]))  

    moveit_config = MoveItConfigsBuilder("theseus", package_name="theseus_moveit") \
        .robot_description(file_path=os.path.join(get_package_share_directory("theseus_description"), "urdf", "theseus.urdf.xacro")) \
        .robot_description_semantic(file_path="config/theseus.srdf") \
        .robot_description_kinematics(file_path="config/kinematics.yaml") \
        .joint_limits(file_path="config/joint_limits.yaml") \
        .pilz_cartesian_limits(file_path="config/pilz_cartesian_limits.yaml") \
        .trajectory_execution(file_path="config/moveit_controllers.yaml") \
        .to_moveit_configs()# TODO: ajust it to recieve different robot models srdf and trajectory controllers

    move_group_node = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[moveit_config.to_dict(), {"use_sim_time": is_sim}, {"publish_robot_description_semantic": True}],
        arguments=["--ros-args", "--log-level", "info"]
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", os.path.join(get_package_share_directory("theseus_moveit"), "rviz", "moveit.rviz")],
        parameters=[moveit_config.robot_description,
                    moveit_config.robot_description_semantic,
                    moveit_config.robot_description_kinematics,
                    moveit_config.joint_limits]
    )

    return LaunchDescription([
        is_sim_arg,
        model_arg,
        move_group_node,
        rviz_node
    ])
