moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  - arm_controller
  - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - gripper_joint 

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_joint_1
      - gripper_joint_2